version: "3"
services:
  # toroinvestimentos:
  #   image: toroinvestimentos/quotesmock
  #   container_name: toroinvestimentos
  #   ports:
  #     - "4008:8080"
  mongostocks:
    build:
      dockerfile: Dockerfile
      context: ./mongodb
    container_name: mongostocks
    image: mongostocks:latest
    ports:
      - "4009:27017"
  backendstocks:
    build:
      dockerfile: Dockerfile
      context: ../torochallenge-backend
    container_name: backendstocks
    image: backendstocks:latest
    links:
      # - toroinvestimentos
      - mongostocks
    ports:
      - "4000:4000"
    depends_on: ["mongostocks"]
  frontendstocks:
    build:
      dockerfile: Dockerfile
      context: ../torochallenge-frontend
    container_name: frontendstocks
    image: frontendstocks:latest
    links:
      # - toroinvestimentos
      - mongostocks
      - backendstocks
    ports:
      - "4200:4200"
    depends_on: ["mongostocks", "backendstocks"]
